[build]
  base = "frontend/"
  publish = "templates/"

[[redirects]]
  from = "/*"
  to = "/main/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 