[build]
  base = "frontend/"
  publish = "dist/"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://patient-health-managementsystem.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  [headers."/*"]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization" 